default: &default
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: test
  password: 123456
  host: localhost

development:
  <<: *default
  database: winejournal

test: &test
  <<: *default
  database: winejournal_test

production:
  <<: *default
  database: winejournal
